"""added field to registration

Revision ID: 522e1ed584b6
Revises: 
Create Date: 2022-04-22 13:54:27.236647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522e1ed584b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrationDB', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reg_activity_status', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrationDB', schema=None) as batch_op:
        batch_op.drop_column('reg_activity_status')

    # ### end Alembic commands ###
